language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

env:
  - GOARCH=amd64
  - GOARCH=386
  - CODECOV_TOKEN="7bc84064-5397-473d-991a-c34c91547e8a"

sudo: true

go_import_path: github.com/fwhezfwhez/cmap

before_install:
 - go get ./...

script:
  # - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -coverprofile=coverage.txt -covermode=atomic
  - go test ./

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
